/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as GestionePrenotazioniRouteImport } from './routes/gestione-prenotazioni'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPrenotazioniRouteImport } from './routes/api/prenotazioni'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionePrenotazioniRoute = GestionePrenotazioniRouteImport.update({
  id: '/gestione-prenotazioni',
  path: '/gestione-prenotazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrenotazioniRoute = ApiPrenotazioniRouteImport.update({
  id: '/api/prenotazioni',
  path: '/api/prenotazioni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gestione-prenotazioni': typeof GestionePrenotazioniRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prenotazioni': typeof ApiPrenotazioniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gestione-prenotazioni': typeof GestionePrenotazioniRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prenotazioni': typeof ApiPrenotazioniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gestione-prenotazioni': typeof GestionePrenotazioniRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/prenotazioni': typeof ApiPrenotazioniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gestione-prenotazioni'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/prenotazioni'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gestione-prenotazioni'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/prenotazioni'
  id:
    | '__root__'
    | '/'
    | '/gestione-prenotazioni'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/prenotazioni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GestionePrenotazioniRoute: typeof GestionePrenotazioniRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPrenotazioniRoute: typeof ApiPrenotazioniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestione-prenotazioni': {
      id: '/gestione-prenotazioni'
      path: '/gestione-prenotazioni'
      fullPath: '/gestione-prenotazioni'
      preLoaderRoute: typeof GestionePrenotazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prenotazioni': {
      id: '/api/prenotazioni'
      path: '/api/prenotazioni'
      fullPath: '/api/prenotazioni'
      preLoaderRoute: typeof ApiPrenotazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GestionePrenotazioniRoute: GestionePrenotazioniRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPrenotazioniRoute: ApiPrenotazioniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
